[package]
name = "lora_ops"
version = "0.1.0"
edition = "2021"

[lib]
name = "lora_ops"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
numpy = "0.19"
ndarray = "0.15.6"
pyo3 = { version = "0.19.0", features = ["extension-module"] } 